# Site settings
title: Patrick W. Kraft | Ph.D. Candidate in the Department of Political Science at Stony Brook University
email: patrick.kraft@stonybrook.edu
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: Patrick W. Kraft
affiliation: Deptartment of Political Science  Stony Brook University

# Social icons
github: pwkraft
linkedin: patrick-kraft-b52319101
researchgate: Patrick_Kraft2
scholar: QTPa1MAAAAAJ
#facebook: username
#deviantart: username
#codepen: username

# Google analytics tracking code:
google_analytics: UA-100572491-1

footer: Created based on Taken theme. Â© 2017 Patrick Kraft

# Build settings
markdown: kramdown
